"""Synthetic demo data for CrimeNet AI. F7.

    python seed.py            # seed into empty tables
    python seed.py --reset    # drop, recreate, reseed
    python seed.py --verify   # assert the three scenarios and print their IDs

Deterministic: one seeded Random drives every choice, inserts happen in a fixed
order, and --reset resets the SERIAL sequences, so both machines get identical
ids. --verify prints a content digest so that can be checked with one string
comparison rather than trust.

Two things are deliberately NOT in the digest: bcrypt salts a password hash
differently every run, and created_at is generated by Postgres at insert time.
Neither is data we authored.

NO REAL PERSONAL DATA. Every name, number, plate and case reference below is
invented. Any resemblance to a real person or record is coincidence.

Topology note, because it is the part that is easy to get wrong. Scenario C
needs removing one person to split the largest component roughly in half, which
is only true if nothing else joins the two sides. So the whole population is
partitioned into halves, every background relationship stays inside its half,
and the two halves meet only at the bridge.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
import time
from datetime import date, timedelta

import networkx as nx
from sqlalchemy import func, select

from app.auth import hash_password
from app.database import Base, SessionLocal, engine, init_db
from app.models import Agency, Entity, Relationship, User

SEED = 20260929
START = date(2019, 1, 1)
END = date(2025, 12, 31)

# ---------------------------------------------------------------- name pools

MALE = ["Rakesh", "Nitin", "Jignesh", "Bhavesh", "Kiran", "Mahesh", "Paresh",
        "Sanjay", "Dinesh", "Hitesh", "Ramesh", "Vipul", "Ashok", "Manish",
        "Jayesh", "Nilesh", "Chirag", "Tushar", "Kartik", "Alpesh", "Rohit",
        "Amit", "Sunil", "Vijay", "Harsh", "Darshan", "Mitul", "Pankaj",
        "Rajesh", "Sandip", "Bhargav", "Devang", "Hardik", "Jatin", "Ketan"]
FEMALE = ["Bhavna", "Nita", "Priya", "Kavita", "Meena", "Rekha", "Sonal",
          "Hetal", "Jyoti", "Falguni", "Trupti", "Asha", "Bhumika", "Dipti",
          "Manisha", "Nishaben", "Rupal", "Shital", "Vaishali", "Zarna"]
MIDDLE = ["kumar", "bhai", "chandra", "prasad", "lal", "ji"]
SURNAMES = ["Patel", "Shah", "Desai", "Chauhan", "Parmar", "Solanki", "Rathod",
            "Vaghela", "Mehta", "Trivedi", "Joshi", "Pandya", "Bhatt", "Modi",
            "Thakkar", "Gohil", "Jadeja", "Makwana", "Zala", "Dave", "Raval",
            "Sheth", "Amin", "Yadav", "Rana", "Chavda", "Bhavsar", "Prajapati"]

CITIES = [("Ahmedabad", "Ahmedabad"), ("Surat", "Surat"), ("Vadodara", "Vadodara"),
          ("Rajkot", "Rajkot"), ("Bhavnagar", "Bhavnagar"), ("Jamnagar", "Jamnagar"),
          ("Gandhinagar", "Gandhinagar"), ("Junagadh", "Junagadh"),
          ("Anand", "Anand"), ("Nadiad", "Kheda"), ("Mehsana", "Mehsana"),
          ("Bharuch", "Bharuch"), ("Navsari", "Navsari"), ("Morbi", "Morbi")]
AREAS = ["Naroda", "Bapunagar", "Vastral", "Kalupur", "Maninagar", "Odhav",
         "Sarkhej", "Gota", "Chandkheda", "Vatva", "Amraiwadi", "Isanpur",
         "Katargam", "Adajan", "Varachha", "Gopipura", "Alkapuri", "Karelibaug"]
STREETS = ["Society", "Chawl", "Nagar", "Estate", "Apartments", "Colony",
           "Tenement", "Flats", "Complex"]

CRIME_TYPES = ["theft", "burglary", "extortion", "cheating", "forgery",
               "narcotics", "vehicle_theft", "assault", "criminal_conspiracy",
               "money_laundering", "kidnapping", "receiving_stolen_property"]
CRIME_STATUS = ["under_investigation", "chargesheeted", "trial", "closed"]
CARRIERS = ["Jio", "Airtel", "Vi", "BSNL"]
MODELS = ["Maruti Swift", "Hyundai i20", "Honda Activa", "Bajaj Pulsar",
          "Tata Nexon", "Mahindra Bolero", "Toyota Innova", "Hero Splendor",
          "TVS Jupiter", "Maruti Eeco", "Ashok Leyland Dost", "Mahindra Pickup"]
COLOURS = ["white", "silver", "black", "blue", "red", "grey"]
ORG_KINDS = ["transport", "scrap_dealer", "jewellery", "real_estate",
             "money_transfer", "logistics"]

# ------------------------------------------------------------ agency + users

AGENCY_SPECS = [
    ("Gujarat Police", "GJ_POLICE"),
    ("Telecom Records Bureau", "TELECOM"),
    ("Regional Transport Office", "RTO"),
]
# The first two usernames match the retired dev_users.py deliberately, so the
# frontend and Krish's notes keep working after a reseed. Every password is the
# username followed by "123" - synthetic accounts, local only, and the demo needs
# known logins.
USER_SPECS = [
    ("investigator", "investigator", "GJ_POLICE"),
    ("admin", "admin", "GJ_POLICE"),
    ("telecom_officer", "investigator", "TELECOM"),
    ("telecom_admin", "admin", "TELECOM"),
    ("rto_officer", "investigator", "RTO"),
    ("rto_admin", "admin", "RTO"),
]


class Seeder:
    def __init__(self, db) -> None:
        self.db = db
        self.rng = random.Random(SEED)
        self.agency: dict[str, int] = {}
        self.rels: list[Relationship] = []
        self.scenarios: dict[str, object] = {}

    # ------------------------------------------------------------- utilities

    def a_date(self, lo: date = START, hi: date = END) -> date:
        return lo + timedelta(days=self.rng.randint(0, (hi - lo).days))

    def person_name(self, female: bool = False) -> str:
        first = self.rng.choice(FEMALE if female else MALE)
        return f"{first} {self.rng.choice(MALE)}{self.rng.choice(MIDDLE)} {self.rng.choice(SURNAMES)}"

    def address(self) -> tuple[str, str, str]:
        city, district = self.rng.choice(CITIES)
        area = self.rng.choice(AREAS)
        line = (f"{self.rng.randint(1, 240)}, {self.rng.choice(SURNAMES)} "
                f"{self.rng.choice(STREETS)}, {area}")
        return line, city, district

    def phone_number(self) -> str:
        return f"+91 {self.rng.choice(['98', '99', '97', '90', '63', '70'])}"\
               f"{self.rng.randint(100, 999)} {self.rng.randint(10000, 99999)}"

    def plate(self) -> str:
        return (f"GJ-{self.rng.randint(1, 38):02d}-"
                f"{self.rng.choice('ABCDEFGHJKLMNPQRSTUVWXYZ')}"
                f"{self.rng.choice('ABCDEFGHJKLMNPQRSTUVWXYZ')}-"
                f"{self.rng.randint(1000, 9999)}")

    def entity(self, etype: str, name: str, agency: str, attributes: dict,
               source_ref: str, shared: bool = False) -> Entity:
        row = Entity(entity_type=etype, name=name, attributes=attributes,
                     agency_id=self.agency[agency], source_ref=source_ref,
                     is_shared=shared)
        self.db.add(row)
        return row

    def link(self, src: Entity, dst: Entity, rel_type: str, agency: str,
             valid_from: date, valid_to: date | None = None,
             confidence: float | None = None, case: str | None = None) -> None:
        self.rels.append(Relationship(
            src_entity_id=src.id, dst_entity_id=dst.id, rel_type=rel_type,
            confidence=confidence if confidence is not None else round(self.rng.uniform(0.62, 1.0), 2),
            valid_from=valid_from, valid_to=valid_to,
            source_case=case or f"FIR/{valid_from.year}/GJ/{self.rng.randint(100, 9999):05d}",
            agency_id=self.agency[agency]))

    # ------------------------------------------------------------ population

    def build_reference_rows(self) -> None:
        for name, code in AGENCY_SPECS:
            row = Agency(name=name, code=code)
            self.db.add(row)
            self.db.flush()
            self.agency[code] = row.id
        for username, role, code in USER_SPECS:
            self.db.add(User(username=username, password_hash=hash_password(f"{username}123"),
                             role=role, agency_id=self.agency[code]))
        self.db.flush()

    def build_population(self) -> dict:
        """Create every entity, tagged into half 0 or half 1.

        Persons sit mostly with the police, but a deliberate slice are telecom
        subscriber records and RTO owner records - that overlap is what makes
        entity resolution meaningful rather than a toy.
        """
        halves: dict[int, dict[str, list[Entity]]] = {
            0: {k: [] for k in ("person", "phone", "vehicle", "location", "crime_event", "organization")},
            1: {k: [] for k in ("person", "phone", "vehicle", "location", "crime_event", "organization")},
        }

        for i in range(300):
            half = 0 if i < 150 else 1
            female = self.rng.random() < 0.22
            # 78% police, 12% telecom subscriber, 10% RTO owner record
            roll = self.rng.random()
            agency = "GJ_POLICE" if roll < 0.78 else ("TELECOM" if roll < 0.90 else "RTO")
            line, city, district = self.address()
            born = date(self.rng.randint(1962, 2003), self.rng.randint(1, 12), self.rng.randint(1, 28))
            attrs = {"dob": born.isoformat(), "gender": "F" if female else "M",
                     "address": line, "city": city}
            # deliberate noise: a fifth have no alias, a tenth no address
            if self.rng.random() < 0.8:
                attrs["alias"] = self.rng.choice(MALE if not female else FEMALE)
            if self.rng.random() < 0.1:
                attrs.pop("address")
            ref = {"GJ_POLICE": f"FIR-PER-{10000 + i}",
                   "TELECOM": f"SUB-{40000 + i}",
                   "RTO": f"RTO-OWN-{70000 + i}"}[agency]
            halves[half]["person"].append(
                self.entity("person", self.person_name(female), agency, attrs, ref,
                            shared=self.rng.random() < 0.12))

        for i in range(120):
            half = 0 if i < 60 else 1
            halves[half]["phone"].append(self.entity(
                "phone", self.phone_number(), "TELECOM",
                {"carrier": self.rng.choice(CARRIERS),
                 "activated": self.a_date(START, date(2024, 6, 30)).isoformat()},
                f"CDR-{88000 + i}", shared=self.rng.random() < 0.15))

        for i in range(90):
            half = 0 if i < 45 else 1
            halves[half]["vehicle"].append(self.entity(
                "vehicle", self.plate(), "RTO",
                {"model": self.rng.choice(MODELS), "colour": self.rng.choice(COLOURS),
                 "year": self.rng.randint(2012, 2024)},
                f"RTO-VEH-{55000 + i}", shared=self.rng.random() < 0.15))

        for i in range(40):
            half = 0 if i < 20 else 1
            line, city, district = self.address()
            halves[half]["location"].append(self.entity(
                "location", line, "GJ_POLICE",
                {"city": city, "district": district, "address": line},
                f"LOC-{31000 + i}", shared=self.rng.random() < 0.2))

        for i in range(80):
            half = 0 if i < 40 else 1
            when = self.a_date()
            ctype = self.rng.choice(CRIME_TYPES)
            case = f"FIR/{when.year}/GJ/{self.rng.randint(100, 9999):05d}"
            halves[half]["crime_event"].append(self.entity(
                "crime_event", f"{ctype.replace('_', ' ').title()} - {case}", "GJ_POLICE",
                {"crime_type": ctype, "status": self.rng.choice(CRIME_STATUS),
                 "case_number": case, "occurred_on": when.isoformat()},
                case))

        for i in range(15):
            half = 0 if i < 8 else 1
            halves[half]["organization"].append(self.entity(
                "organization",
                f"{self.rng.choice(SURNAMES)} {self.rng.choice(['Traders', 'Transport', 'Enterprise', 'Agency', 'and Sons'])}",
                "GJ_POLICE",
                {"org_type": self.rng.choice(ORG_KINDS),
                 "registration_no": f"GJ/REG/{self.rng.randint(10000, 99999)}"},
                f"ORG-{9000 + i}")
            )

        self.db.flush()   # assigns every id in insert order
        return halves

    # -------------------------------------------------------- relationships

    def build_background(self, halves: dict) -> None:
        """Edges strictly inside one half. Nothing here may cross."""
        for half, pools in halves.items():
            people = pools["person"]
            # 8 per half are left with no edges at all - the PRD asks for
            # deliberate dead-end nodes so the data does not look manufactured
            core = people[:-8]

            # spanning tree first, so the half is guaranteed to be one component
            for i in range(1, len(core)):
                partner = core[self.rng.randint(0, i - 1)]
                self.link(core[i], partner,
                          self.rng.choice(["co_accused", "family_of", "transacted_with"]),
                          "GJ_POLICE", self.a_date())

            for _ in range(40):
                a, b = self.rng.sample(core, 2)
                self.link(a, b, self.rng.choice(["co_accused", "transacted_with"]),
                          "GJ_POLICE", self.a_date())

            for phone in pools["phone"]:
                self.link(self.rng.choice(core), phone, "owns", "TELECOM",
                          self.a_date(START, date(2024, 1, 1)))
            for i in range(0, len(pools["phone"]) - 1, 2):
                started = self.a_date()
                self.link(pools["phone"][i], pools["phone"][i + 1], "called", "TELECOM",
                          started, started + timedelta(days=self.rng.randint(1, 400)))

            for vehicle in pools["vehicle"]:
                self.link(self.rng.choice(core), vehicle, "owns", "RTO",
                          self.a_date(START, date(2024, 1, 1)))
            for vehicle in pools["vehicle"][:20]:
                self.link(vehicle, self.rng.choice(pools["location"]), "registered_at",
                          "RTO", self.a_date())

            for event in pools["crime_event"]:
                when = date.fromisoformat(event.attributes["occurred_on"])
                for person in self.rng.sample(core, self.rng.randint(1, 2)):
                    self.link(person, event,
                              self.rng.choice(["suspect_in", "suspect_in", "witness_in"]),
                              "GJ_POLICE", when, case=event.attributes["case_number"])
                self.link(event, self.rng.choice(pools["location"]), "present_at",
                          "GJ_POLICE", when, case=event.attributes["case_number"])

            for org in pools["organization"]:
                for person in self.rng.sample(core, self.rng.randint(1, 3)):
                    self.link(person, org, "transacted_with", "GJ_POLICE", self.a_date())

    # ------------------------------------------------------------- scenarios

    def scenario_a_ring(self, halves: dict) -> None:
        """A visible ring of 12 around one central figure, growing 2019 -> 2025.

        Uses entities from all three agencies, and the introduction years are
        staggered so the timeline in F6 has something to replay: 3 nodes in 2019,
        the full ring by 2025.
        """
        pool = halves[0]
        ring = pool["person"][:12]
        boss, members = ring[0], ring[1:]
        # Tag them. The general population's source_ref prefix depends on a random
        # agency draw, so it is not a reliable handle - an explicit marker is.
        boss.attributes = {**boss.attributes, "scenario": "A_center"}
        for member in members:
            member.attributes = {**member.attributes, "scenario": "A_member"}
        years = [2019, 2019, 2020, 2020, 2021, 2021, 2022, 2023, 2023, 2024, 2025]
        for member, year in zip(members, years):
            when = date(year, self.rng.randint(1, 12), self.rng.randint(1, 28))
            self.link(boss, member, "co_accused", "GJ_POLICE", when, confidence=0.9,
                      case=f"FIR/{year}/GJ/{self.rng.randint(1000, 9999):05d}")
        # lieutenants, so it reads as a ring rather than a star
        for i in range(1, 6):
            self.link(members[i], members[i + 1], "co_accused", "GJ_POLICE",
                      date(2022 + (i % 3), self.rng.randint(1, 12), 15), confidence=0.85)
        # telecom and RTO records pull the other two agencies into the ring
        for i, member in enumerate(members[:5]):
            self.link(member, pool["phone"][i], "owns", "TELECOM", date(2020 + i % 4, 6, 1))
        for i, member in enumerate(members[5:9]):
            self.link(member, pool["vehicle"][i], "owns", "RTO", date(2021 + i % 3, 3, 1))
        self.link(boss, pool["phone"][10], "owns", "TELECOM", date(2019, 4, 2))
        self.link(boss, pool["vehicle"][10], "owns", "RTO", date(2019, 7, 9))
        self.scenarios["ring_center_id"] = boss.id
        self.scenarios["ring_member_ids"] = [p.id for p in ring]

    def scenario_b_duplicate(self, halves: dict) -> None:
        """One real person recorded twice, in two agencies, spelled differently.

        Shares a phone and an address with itself, and the DOBs are days apart.
        Those are the signals resolution.py scores in F8; the target is ~0.85.
        Both records sit in the SAME half, or they would form a second bridge
        and break scenario C.
        """
        pool = halves[0]
        born = date(1984, 7, 19)
        line, city, district = self.address()

        police = self.entity("person", "Rakesh Kumarbhai Yadav", "GJ_POLICE",
                             {"dob": born.isoformat(), "gender": "M", "alias": "Rakhu",
                              "address": line, "city": city, "scenario": "B_record_a"},
                             "FIR-PER-20881", shared=True)
        rto = self.entity("person", "Rakesh Kumar Yadhav", "RTO",
                          {"dob": (born + timedelta(days=2)).isoformat(), "gender": "M",
                           "alias": "Rakesh", "address": line, "city": city,
                           "scenario": "B_record_b"},
                          "RTO-OWN-70992", shared=True)
        phone = self.entity("phone", self.phone_number(), "TELECOM",
                            {"carrier": "Jio", "activated": "2020-02-11"},
                            "CDR-88999", shared=True)
        home = self.entity("location", line, "GJ_POLICE",
                           {"city": city, "district": district, "address": line},
                           "LOC-31999", shared=True)
        self.db.flush()

        for record in (police, rto):
            self.link(record, phone, "owns", "TELECOM", date(2020, 2, 11))
            self.link(record, home, "present_at", "GJ_POLICE", date(2020, 3, 1))
        # attach both into the same half so neither is an island
        self.link(police, pool["person"][20], "co_accused", "GJ_POLICE", date(2021, 5, 4))
        self.link(rto, pool["vehicle"][3], "owns", "RTO", date(2022, 8, 17))
        self.scenarios["duplicate_pair"] = [police.id, rto.id]
        self.scenarios["duplicate_shared"] = {"phone_id": phone.id, "location_id": home.id}

    def scenario_c_bridge(self, halves: dict) -> None:
        """The only edge set joining the two halves.

        Shared, so both an investigator and an admin can see the split happen.
        """
        bridge = self.entity("person", "Nitin Ramanbhai Chauhan", "GJ_POLICE",
                             {"dob": "1979-11-03", "gender": "M", "alias": "Nittu",
                              "address": "14, Gohil Estate, Odhav", "city": "Ahmedabad",
                              "scenario": "C_bridge"},
                             "FIR-PER-20999", shared=True)
        self.db.flush()
        for half in (0, 1):
            for person in halves[half]["person"][30:33]:
                self.link(bridge, person, "transacted_with", "GJ_POLICE",
                          date(2021 + half, 4 + half, 12), confidence=0.78)
        self.scenarios["bridge_id"] = bridge.id

    # ------------------------------------------------------------------ run

    def run(self) -> dict:
        self.build_reference_rows()
        halves = self.build_population()
        self.build_background(halves)
        self.scenario_a_ring(halves)
        self.scenario_b_duplicate(halves)
        self.scenario_c_bridge(halves)
        self.db.add_all(self.rels)
        self.db.commit()
        return self.scenarios


# --------------------------------------------------------------- verify side


def load_graph(db) -> nx.Graph:
    g = nx.Graph()
    for eid, etype in db.execute(select(Entity.id, Entity.entity_type)):
        g.add_node(eid, entity_type=etype)
    for src, dst in db.execute(select(Relationship.src_entity_id, Relationship.dst_entity_id)):
        if src != dst:
            g.add_edge(src, dst)
    return g


def content_digest(db) -> str:
    """SHA-256 over the data we authored, in id order.

    Excludes password_hash (bcrypt salts differ per run) and created_at
    (Postgres generates it), neither of which we chose.
    """
    h = hashlib.sha256()
    for name, code in db.execute(select(Agency.name, Agency.code).order_by(Agency.id)):
        h.update(f"A|{name}|{code}\n".encode())
    for username, role, aid in db.execute(select(User.username, User.role, User.agency_id).order_by(User.id)):
        h.update(f"U|{username}|{role}|{aid}\n".encode())
    for row in db.execute(select(Entity.entity_type, Entity.name, Entity.attributes,
                                 Entity.agency_id, Entity.source_ref, Entity.is_shared)
                          .order_by(Entity.id)):
        h.update(("E|" + "|".join([row[0], row[1], json.dumps(row[2], sort_keys=True),
                                   str(row[3]), str(row[4]), str(row[5])]) + "\n").encode())
    for row in db.execute(select(Relationship.src_entity_id, Relationship.dst_entity_id,
                                 Relationship.rel_type, Relationship.confidence,
                                 Relationship.valid_from, Relationship.valid_to,
                                 Relationship.source_case, Relationship.agency_id)
                          .order_by(Relationship.id)):
        h.update(("R|" + "|".join(str(v) for v in row) + "\n").encode())
    return h.hexdigest()


def _by_marker(db, marker: str) -> Entity | None:
    """Fetch a scenario entity by its attributes["scenario"] tag."""
    return db.scalar(select(Entity).where(Entity.attributes["scenario"].astext == marker))


def counts(db) -> dict[str, int]:
    out = {"agencies": db.scalar(select(func.count()).select_from(Agency)),
           "users": db.scalar(select(func.count()).select_from(User)),
           "relationships": db.scalar(select(func.count()).select_from(Relationship))}
    for etype, n in db.execute(select(Entity.entity_type, func.count())
                               .group_by(Entity.entity_type).order_by(Entity.entity_type)):
        out[etype] = n
    out["entities"] = db.scalar(select(func.count()).select_from(Entity))
    return out


def verify(db) -> bool:
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        ok = ok and passed
        print(f"  {'PASS' if passed else 'FAIL'}  {label}" + (f"  -> {detail}" if detail else ""))

    print("Counts")
    for key, value in counts(db).items():
        print(f"  {key:<16} {value}")

    g = load_graph(db)
    print(f"\nGraph: {g.number_of_nodes()} nodes, {g.number_of_edges()} edges, "
          f"{nx.number_connected_components(g)} components")

    # ---- Scenario A
    print("\nScenario A - crime ring")
    boss = _by_marker(db, "A_center")
    check("central figure exists", boss is not None)
    if boss is not None:
        ring = set(nx.single_source_shortest_path_length(g, boss.id, cutoff=1))
        people = [n for n in ring if g.nodes[n].get("entity_type") == "person"]
        years = sorted({r for (r,) in db.execute(
            select(func.extract("year", Relationship.valid_from))
            .where(Relationship.src_entity_id == boss.id))})
        check("ring has 12+ people around it", len(people) >= 12, f"{len(people)} people")
        check("ring spans multiple entity types",
              len({g.nodes[n].get("entity_type") for n in ring}) >= 3,
              str(sorted({g.nodes[n].get("entity_type") for n in ring})))
        check("ring grows over time", len(years) >= 5, f"years {[int(y) for y in years]}")
        print(f"       ring_center_id = {boss.id}")

    # ---- Scenario B
    print("\nScenario B - duplicate identity")
    a = _by_marker(db, "B_record_a")
    b = _by_marker(db, "B_record_b")
    check("both records exist", a is not None and b is not None)
    if a is not None and b is not None:
        check("different agencies", a.agency_id != b.agency_id)
        check("names differ but are close", a.name != b.name, f"{a.name!r} vs {b.name!r}")
        shared = set(g.neighbors(a.id)) & set(g.neighbors(b.id))
        kinds = sorted({g.nodes[n].get("entity_type") for n in shared})
        check("share a phone and a location", {"phone", "location"} <= set(kinds), str(kinds))
        check("dob within a week",
              abs(date.fromisoformat(a.attributes["dob"]) - date.fromisoformat(b.attributes["dob"])).days <= 7)
        print(f"       duplicate_pair = [{a.id}, {b.id}]  shared = {sorted(shared)}")

    # ---- Scenario C
    print("\nScenario C - bridge node")
    bridge = _by_marker(db, "C_bridge")
    check("bridge exists", bridge is not None)
    if bridge is not None:
        biggest = max(nx.connected_components(g), key=len)
        check("bridge is in the largest component", bridge.id in biggest, f"largest = {len(biggest)}")
        cut = g.copy()
        cut.remove_node(bridge.id)
        pieces = sorted((c for c in nx.connected_components(cut) if c & biggest), key=len, reverse=True)
        check("removal splits it in two", len(pieces) >= 2,
              f"pieces {[len(p) for p in pieces[:4]]}")
        if len(pieces) >= 2:
            big, second = len(pieces[0]), len(pieces[1])
            check("halves are roughly equal", second >= 0.35 * (big + second),
                  f"{big} vs {second} ({second / (big + second):.0%} / {big / (big + second):.0%})")
        print(f"       bridge_id = {bridge.id}")

    print(f"\nContent digest: {content_digest(db)}")
    print("  Both machines must print the same digest. Password hashes and")
    print("  created_at are excluded - bcrypt salts and Postgres clocks differ.")
    return ok


# ---------------------------------------------------------------------- main


def main() -> int:
    ap = argparse.ArgumentParser(description="Seed CrimeNet AI demo data.")
    ap.add_argument("--reset", action="store_true", help="drop, recreate and reseed")
    ap.add_argument("--verify", action="store_true", help="check the three scenarios")
    args = ap.parse_args()

    if args.verify and not args.reset:
        with SessionLocal() as db:
            return 0 if verify(db) else 1

    started = time.perf_counter()
    if args.reset:
        print("dropping and recreating every table")
        Base.metadata.drop_all(bind=engine)
    init_db()

    with SessionLocal() as db:
        if db.scalar(select(func.count()).select_from(Entity)):
            print("Tables already hold data. Use --reset to wipe and reseed.", file=sys.stderr)
            return 1
        print(f"seeding with SEED={SEED}")
        Seeder(db).run()

    with SessionLocal() as db:
        for key, value in counts(db).items():
            print(f"  {key:<16} {value}")
        print(f"done in {time.perf_counter() - started:.1f}s")
        if args.verify:
            print()
            return 0 if verify(db) else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
