"""Password hashing, JWT issue and decode, and the role dependencies.

Uses the bcrypt library directly and PyJWT, both deliberately: passlib breaks
against bcrypt 4.x and later with a version-detection error, and python-jose is
barely maintained. See the rejected-technology table in CLAUDE.md Section 2.

Shared file.
"""

from datetime import datetime, timedelta, timezone

import bcrypt
import jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.models import User

ALGORITHM = "HS256"

# tokenUrl is what /docs uses for its Authorize button.
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")

_UNAUTHORIZED = {"WWW-Authenticate": "Bearer"}


def hash_password(plain: str) -> str:
    """bcrypt hash, cost from gensalt()'s default.

    bcrypt rejects passwords over 72 bytes rather than truncating them, which is
    fine here - every password in this project is generated by dev_users.py or
    seed.py.
    """
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def verify_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except ValueError:
        # Malformed hash, or a password over bcrypt's 72-byte limit. Neither is a
        # server error - it is simply a failed login.
        return False


def create_access_token(user: User) -> str:
    """Access token only, 12-hour default expiry. No refresh token by design."""
    expires_at = datetime.now(timezone.utc) + timedelta(hours=settings.jwt_expire_hours)
    payload = {
        "sub": str(user.id),
        "username": user.username,
        "role": user.role,
        "agency_id": user.agency_id,
        "exp": expires_at,
    }
    return jwt.encode(payload, settings.jwt_secret, algorithm=ALGORITHM)


def decode_token(token: str) -> dict:
    """Verify signature and expiry, returning the claims."""
    try:
        return jwt.decode(token, settings.jwt_secret, algorithms=[ALGORITHM])
    except jwt.ExpiredSignatureError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="token has expired",
            headers=_UNAUTHORIZED,
        ) from exc
    except jwt.InvalidTokenError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid token",
            headers=_UNAUTHORIZED,
        ) from exc


def get_current_user(
    token: str = Depends(oauth2_scheme),
    db: Session = Depends(get_db),
) -> User:
    """Resolve the bearer token to a live User row.

    The row is re-read on every request rather than trusted from the claims, so
    a user deleted or moved between agencies cannot keep acting on a stale token.
    """
    claims = decode_token(token)
    subject = claims.get("sub")
    if subject is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="token is missing its subject claim",
            headers=_UNAUTHORIZED,
        )
    user = db.get(User, int(subject))
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="user no longer exists",
            headers=_UNAUTHORIZED,
        )
    return user


def require_admin(user: User = Depends(get_current_user)) -> User:
    """403 for an investigator, per F1."""
    if user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="this action requires the admin role",
        )
    return user
